#pragma once

#define STAGE_GRID_MESH_CORRIDOR	0
#define STAGE_GRID_MESH_STAIR		1
#define STAGE_GRID_MESH_TYPES		2

#define STAGE_GRID_CORRIDOR_FLOOR				0
#define STAGE_GRID_CORRIDOR_WALL				1
#define STAGE_GRID_CORRIDOR_WALL_BASE			2
#define STAGE_GRID_CORRIDOR_WALL_DOOR			3
#define STAGE_GRID_CORRIDOR_WALL_DOOR_BASE		4
#define STAGE_GRID_CORRIDOR_PHILAR				5
#define STAGE_GRID_CORRIDOR_CEILING1			6
#define STAGE_GRID_CORRIDOR_CEILING2			7
#define STAGE_GRID_CORRIDOR_CEILING3			8
#define STAGE_GRID_CORRIDOR_CEILING_ARCH		9
#define STAGE_GRID_CORRIDOR_CEILING_ARCH_WALL	10
#define STAGE_GRID_CORRIDOR_FLOOR_CLAMP			11
#define STAGE_GRID_CORRIDOR_WALL_CLAMP1			12
#define STAGE_GRID_CORRIDOR_WALL_CLAMP1_BASE	13
#define STAGE_GRID_CORRIDOR_CANDLE				14
#define STAGE_GRID_CORRIDOR_CANDLELABRA			15
#define STAGE_GRID_CORRIDOR_CANDLEFLAME			16
#define STAGE_GRID_CORRIDOR_FLOOR1				17
#define STAGE_GRID_CORRIDOR_FLOOR2				18
#define STAGE_GRID_CORRIDOR_FLOOR3				19
#define STAGE_GRID_CORRIDOR_PHILAR1				20
#define STAGE_GRID_CORRIDOR_PHILAR2				21
#define STAGE_GRID_CORRIDOR_NUM					22

#define CUSTOMDEPTH_INTERACTABLE_ITEM		100
#define CUSTOMDEPTH_PLAYERCHARACTER			101
#define CUSTOMDEPTH_INTERACTABLE_ITEM_BUSY	102
#define CUSTOMDEPTH_ENEMYCHARACTER			103

#define INTERACTABLE_ITEM_POTION_BLUE		0
#define INTERACTABLE_ITEM_POTION_GREEN		1
#define INTERACTABLE_ITEM_GEMSTONE_BLUE		2
#define INTERACTABLE_ITEM_GEMSTONE_YELLOW	3
#define INTERACTABLE_ITEM_GEMSTONE_RED		4
#define INTERACTABLE_ITEM_GEMSTONE_GREEN	5
#define INTERACTABLE_ITEM_GEMSTONE_PURPLE	6
#define INTERACTABLE_ITEM_GEMSTONE_PINK		7
#define INTERACTABLE_ITEM_NUM				8

#define INTERACTABLE_ITEM_STATE_CLOSED	0
#define INTERACTABLE_ITEM_STATE_OPEN_L	1
#define INTERACTABLE_ITEM_STATE_OPEN_R	2
#define INTERACTABLE_ITEM_STATE_LOCKED	3

#define ITEM_CATEGORY_DISPOSABLE		0
#define ITEM_CATEGORY_EQUIPMENT			1
#define ITEM_CATEGORY_ETC				2
#define ITEM_CATEGORY_NUM				3

#define ITEM_RARITY_NORMAL		1
#define ITEM_RARITY_RARE		2
#define ITEM_RARITY_EPIC		3
#define ITEM_RARITY_LEGENDARY	4

#define ITEM_DESCRIPTION_DAMAGE			0
#define ITEM_DESCRIPTION_DEFENCE		1
#define ITEM_DESCRIPTION_HEALTH_RESTORE	2
#define ITEM_DESCRIPTION_NUM			3

#define DAMAGE_WIDGET_TYPE_MINION	0
#define DAMAGE_WIDGET_TYPE_PLAYER	1
// Item Rarity Colors
const FLinearColor ITEM_COLOR_NORMAL = FLinearColor(0.5f, 0.5f, 0.5f, 1.0f); // Gray
const FLinearColor ITEM_COLOR_RARE = FLinearColor(0.0f, 0.0f, 1.0f, 1.0f);   // Blue
const FLinearColor ITEM_COLOR_EPIC = FLinearColor(0.5f, 0.0f, 0.5f, 1.0f);   // Purple
const FLinearColor ITEM_COLOR_LEGENDARY = FLinearColor(0.0f, 1.0f, 0.0f, 1.0f); // Light Green (Full Green for now)

const FLinearColor DAMAGE_COLOR_PLAYER = FLinearColor(1.f, 1.f, 1.f, 1.0f);
const FLinearColor DAMAGE_COLOR_MINION = FLinearColor(0.3f, 0.2f, 1.0f, 1.0f);

#define EQUIPMENT_SWORD			0
#define EQUIPMENT_HELMET		1
#define EQUIPMENT_GLOVE			2
#define EQUIPMENT_SHOSE			3
#define EQUIPMENT_TORSO1		4
#define EQUIPMENT_TORSO2		5
#define EQUIPMENT_TORSO3		6
#define EQUIPMENT_PANTS			7
#define EQUIPMENT_NUM			8

#define COLLISION_CHANNEL_PLAYER_GAZE	ECollisionChannel::ECC_GameTraceChannel1

#define ENEMYCHARACTER_MINION			0
#define ENEMYCHARACTER_MINION_RANGED	1
#define ENEMYCHARACTER_MINION_SIEZE		2
#define ENEMYCHARACTER_NUM				3

#define ENEMYCHARACTER_ACTIONTYPE_MELLEEATTACK	0
#define ENEMYCHARACTER_ACTIONTYPE_RANGEDATTACK	1

#define ENEMYCHARACTER_HIT_REACT_FRONT	0
#define ENEMYCHARACTER_HIT_REACT_BACK	1
#define ENEMYCHARACTER_HIT_REACT_LEFT	2
#define ENEMYCHARACTER_HIT_REACT_RIGHT	3

#define ENEMYCHARACTER_COMBOATTACK_AA	0
#define ENEMYCHARACTER_COMBOATTACK_AB	1
#define ENEMYCHARACTER_COMBOATTACK_AC	2
#define ENEMYCHARACTER_COMBOATTACK_AD	3
#define ENEMYCHARACTER_COMBOATTACK_BA	4
#define ENEMYCHARACTER_COMBOATTACK_BB	5
#define ENEMYCHARACTER_COMBOATTACK_BC	6
#define ENEMYCHARACTER_COMBOATTACK_BD	7
#define ENEMYCHARACTER_COMBOATTACK_BE	8
#define ENEMYCHARACTER_COMBOATTACK_CA	9
#define ENEMYCHARACTER_COMBOATTACK_CB	10
#define ENEMYCHARACTER_COMBOATTACK_CC	11
#define ENEMYCHARACTER_COMBOATTACK_CD	12
#define ENEMYCHARACTER_COMBOATTACK_CE	13
#define ENEMYCHARACTER_COMBOATTACK_NUM	14

#define ENEMYCHARACTER_RANGED_AGGRO		0
#define ENEMYCHARACTER_RANGED_FIRE		1
#define ENEMYCHARACTER_RANGED_TURN		2
#define ENEMYCHARACTER_RANGED_NUM		3

#define ENEMYCHARACTER_SIEZE_PLANT		0
#define ENEMYCHARACTER_SIEZE_PLANT_FIRE	1
#define ENEMYCHARACTER_SIEZE_UNPLANT	2
#define ENEMYCHARACTER_SIEZE_NUM		3

#define ENEMYCHARACTER_COMBOATTACK_A_MAX	4
#define ENEMYCHARACTER_COMBOATTACK_B_MAX	5
#define ENEMYCHARACTER_COMBOATTACK_C_MAX	5

#define PARTICLE_MINION_SPAWN				0
#define PARTICLE_MINION_MELLEE_HIT_IMPACT	1
#define PARTICLE_MINION_RANGED_PROJECTILE	2
#define PARTICLE_PLAYER_HIT_MELLEE_IMPACT	3
#define PARTICLE_PLAYER_HIT_COUNTER_SUCCEEDED	4
#define PARTICLE_MINION_DEAD_RECALL			5
#define PARTICLE_NUM						6

#define PLAYER_ANIMATION_SEQUENCE_LMB_ATTACK1		0
#define PLAYER_ANIMATION_SEQUENCE_LMB_ATTACK2		1
#define PLAYER_ANIMATION_SEQUENCE_LMB_ATTACK3		2
#define PLAYER_ANIMATION_SEQUENCE_RMB_ATTACK1		3
#define PLAYER_ANIMATION_SEQUENCE_RMB_ATTACK2		4
#define PLAYER_ANIMATION_SEQUENCE_RMB_ATTACK3		5
#define PLAYER_ANIMATION_SEQUENCE_COUNTER_READY		6
#define PLAYER_ANIMATION_SEQUENCE_COUNTER_IDLE		7
#define PLAYER_ANIMATION_SEQUENCE_COUNTER_RELEASE	8
#define PLAYER_ANIMATION_SEQUENCE_COUNTER_ATTACK	9
#define PLAYER_ANIMATION_SEQUENCE_EXECUTE			10
#define PLAYER_ANIMATION_SEQUENCE_ROLL				11
#define PLAYER_ANIMATION_SEQUENCE_NUM				12

#define PLAYER_INPUT_LMB	0
#define PLAYER_INPUT_RMB	1

#define PLAYER_SOCKET_WEAPON_R	TEXT("Weapon_R")

#define ATTACK_TYPE_MELLE	0
#define ATTACK_TYPE_RANGED	1
#define ATTACK_TYPE_MAGIC	2
#define ATTACK_TYPE_NUM		3

enum class ProjectileParticle
{
	MinionFire
};

enum class PressingButton
{
	Forward = 1,
	Back = 1 << 1,
	Left = 1 << 2,
	Right = 1 << 3
};