#pragma once

#define STAGE_GRID_MESH_CORRIDOR	0
#define STAGE_GRID_MESH_STAIR		1
#define STAGE_GRID_MESH_TYPES		2

#define STAGE_GRID_CORRIDOR_FLOOR				0
#define STAGE_GRID_CORRIDOR_WALL				1
#define STAGE_GRID_CORRIDOR_WALL_BASE			2
#define STAGE_GRID_CORRIDOR_WALL_DOOR			3
#define STAGE_GRID_CORRIDOR_WALL_DOOR_BASE		4
#define STAGE_GRID_CORRIDOR_PHILAR				5
#define STAGE_GRID_CORRIDOR_CEILING1			6
#define STAGE_GRID_CORRIDOR_CEILING2			7
#define STAGE_GRID_CORRIDOR_CEILING3			8
#define STAGE_GRID_CORRIDOR_CEILING_ARCH		9
#define STAGE_GRID_CORRIDOR_CEILING_ARCH_WALL	10
#define STAGE_GRID_CORRIDOR_FLOOR_CLAMP			11
#define STAGE_GRID_CORRIDOR_WALL_CLAMP1			12
#define STAGE_GRID_CORRIDOR_WALL_CLAMP1_BASE	13
#define STAGE_GRID_CORRIDOR_CANDLE				14
#define STAGE_GRID_CORRIDOR_CANDLELABRA			15
#define STAGE_GRID_CORRIDOR_CANDLEFLAME			16
#define STAGE_GRID_CORRIDOR_FLOOR1				17
#define STAGE_GRID_CORRIDOR_FLOOR2				18
#define STAGE_GRID_CORRIDOR_FLOOR3				19
#define STAGE_GRID_CORRIDOR_PHILAR1				20
#define STAGE_GRID_CORRIDOR_PHILAR2				21
#define STAGE_GRID_CORRIDOR_NUM					22

#define CUSTOMDEPTH_INTERACTABLE_ITEM		100
#define CUSTOMDEPTH_PLAYERCHARACTER			101
#define CUSTOMDEPTH_INTERACTABLE_ITEM_BUSY	102
#define CUSTOMDEPTH_ENEMYCHARACTER			103

#define INTERACTABLE_ITEM_POTION_BLUE		0
#define INTERACTABLE_ITEM_POTION_GREEN		1
#define INTERACTABLE_ITEM_GEMSTONE_BLUE		2
#define INTERACTABLE_ITEM_GEMSTONE_YELLOW	3
#define INTERACTABLE_ITEM_GEMSTONE_RED		4
#define INTERACTABLE_ITEM_GEMSTONE_GREEN	5
#define INTERACTABLE_ITEM_GEMSTONE_PURPLE	6
#define INTERACTABLE_ITEM_GEMSTONE_PINK		7
#define INTERACTABLE_ITEM_NUM				8

#define INTERACTABLE_ITEM_STATE_CLOSED	0
#define INTERACTABLE_ITEM_STATE_OPEN_L	1
#define INTERACTABLE_ITEM_STATE_OPEN_R	2
#define INTERACTABLE_ITEM_STATE_LOCKED	3

#define COLLISION_CHANNEL_PLAYER_GAZE	ECollisionChannel::ECC_GameTraceChannel1

#define ENEMYCHARACTER_MINION			0
#define ENEMYCHARACTER_MINION_RANGED	1
#define ENEMYCHARACTER_MINION_SIEZE		2
#define ENEMYCHARACTER_NUM				3

#define ENEMYCHARACTER_ACTIONTYPE_MELLEEATTACK	0
#define ENEMYCHARACTER_ACTIONTYPE_RANGEDATTACK	1

#define ENEMYCHARACTER_COMBOATTACK_AA	0
#define ENEMYCHARACTER_COMBOATTACK_AB	1
#define ENEMYCHARACTER_COMBOATTACK_AC	2
#define ENEMYCHARACTER_COMBOATTACK_AD	3
#define ENEMYCHARACTER_COMBOATTACK_BA	4
#define ENEMYCHARACTER_COMBOATTACK_BB	5
#define ENEMYCHARACTER_COMBOATTACK_BC	6
#define ENEMYCHARACTER_COMBOATTACK_BD	7
#define ENEMYCHARACTER_COMBOATTACK_BE	8
#define ENEMYCHARACTER_COMBOATTACK_CA	9
#define ENEMYCHARACTER_COMBOATTACK_CB	10
#define ENEMYCHARACTER_COMBOATTACK_CC	11
#define ENEMYCHARACTER_COMBOATTACK_CD	12
#define ENEMYCHARACTER_COMBOATTACK_CE	13
#define ENEMYCHARACTER_COMBOATTACK_NUM	14

#define ENEMYCHARACTER_RANGED_AGGRO		0
#define ENEMYCHARACTER_RANGED_FIRE		1
#define ENEMYCHARACTER_RANGED_TURN		2
#define ENEMYCHARACTER_RANGED_NUM		3

#define ENEMYCHARACTER_SIEZE_PLANT		0
#define ENEMYCHARACTER_SIEZE_PLANT_FIRE	1
#define ENEMYCHARACTER_SIEZE_UNPLANT	2
#define ENEMYCHARACTER_SIEZE_NUM		3

#define ENEMYCHARACTER_COMBOATTACK_A_MAX	4
#define ENEMYCHARACTER_COMBOATTACK_B_MAX	5
#define ENEMYCHARACTER_COMBOATTACK_C_MAX	5

#define PARTICLE_MINION_SPAWN				0
#define PARTICLE_MINION_MELLEE_HIT_IMPACT	1
#define PARTICLE_MINION_RANGED_PROJECTILE	2
#define PARTICLE_NUM						3

enum class ProjectileParticle
{
	MinionFire
};