#pragma once

#define STAGE_GRID_MESH_CORRIDOR	0
#define STAGE_GRID_MESH_STAIR		1
#define STAGE_GRID_MESH_TYPES		2

#define STAGE_GRID_CORRIDOR_FLOOR				0
#define STAGE_GRID_CORRIDOR_WALL				1
#define STAGE_GRID_CORRIDOR_WALL_BASE			2
#define STAGE_GRID_CORRIDOR_WALL_DOOR			3
#define STAGE_GRID_CORRIDOR_WALL_DOOR_BASE		4
#define STAGE_GRID_CORRIDOR_PHILAR				5
#define STAGE_GRID_CORRIDOR_CEILING1			6
#define STAGE_GRID_CORRIDOR_CEILING2			7
#define STAGE_GRID_CORRIDOR_CEILING3			8
#define STAGE_GRID_CORRIDOR_CEILING_ARCH		9
#define STAGE_GRID_CORRIDOR_CEILING_ARCH_WALL	10
#define STAGE_GRID_CORRIDOR_FLOOR_CLAMP			11
#define STAGE_GRID_CORRIDOR_WALL_CLAMP1			12
#define STAGE_GRID_CORRIDOR_WALL_CLAMP1_BASE	13
#define STAGE_GRID_CORRIDOR_CANDLE				14
#define STAGE_GRID_CORRIDOR_CANDLELABRA			15
#define STAGE_GRID_CORRIDOR_CANDLEFLAME			16
#define STAGE_GRID_CORRIDOR_FLOOR1				17
#define STAGE_GRID_CORRIDOR_FLOOR2				18
#define STAGE_GRID_CORRIDOR_FLOOR3				19
#define STAGE_GRID_CORRIDOR_PHILAR1				20
#define STAGE_GRID_CORRIDOR_PHILAR2				21
#define STAGE_GRID_CORRIDOR_NUM					22

#define CUSTOMDEPTH_INTERACTABLE_ITEM		100
#define CUSTOMDEPTH_PLAYERCHARACTER			101
#define CUSTOMDEPTH_INTERACTABLE_ITEM_BUSY	102
#define CUSTOMDEPTH_ENEMYCHARACTER			103

#define INTERACTABLE_ITEM_POTION_BLUE		0
#define INTERACTABLE_ITEM_POTION_GREEN		1
#define INTERACTABLE_ITEM_GEMSTONE_BLUE		2
#define INTERACTABLE_ITEM_GEMSTONE_YELLOW	3
#define INTERACTABLE_ITEM_GEMSTONE_RED		4
#define INTERACTABLE_ITEM_GEMSTONE_GREEN	5
#define INTERACTABLE_ITEM_GEMSTONE_PURPLE	6
#define INTERACTABLE_ITEM_GEMSTONE_PINK		7
#define INTERACTABLE_ITEM_NUM				8

#define INTERACTABLE_ITEM_STATE_CLOSED	0
#define INTERACTABLE_ITEM_STATE_OPEN_L	1
#define INTERACTABLE_ITEM_STATE_OPEN_R	2
#define INTERACTABLE_ITEM_STATE_LOCKED	3

#define COLLISION_CHANNEL_PLAYER_GAZE	ECollisionChannel::ECC_GameTraceChannel1

#define ENEMYCHARACTER_MINION	0
#define ENEMYCHARACTER_NUM		1

#define ENEMYCHARACTER_COMBOATTACK_A	0
#define ENEMYCHARACTER_COMBOATTACK_B	1
#define ENEMYCHARACTER_COMBOATTACK_C	2

#define ENEMYCHARACTER_COMBOATTACK_A_MAX	4
#define ENEMYCHARACTER_COMBOATTACK_B_MAX	5
#define ENEMYCHARACTER_COMBOATTACK_C_MAX	5